// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB3WmtgbN_RikmTNtl-9FK0jLmM2xBJFA',
    appId: '1:920531153302:web:a4f8646064995f3b10edb7',
    messagingSenderId: '920531153302',
    projectId: 'expense-trackeryt',
    authDomain: 'expense-trackeryt.firebaseapp.com',
    storageBucket: 'expense-trackeryt.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeu19JoouRuaylY8VLrnAl2wS3YNYdg_E',
    appId: '1:920531153302:android:cafdd278aa730fe710edb7',
    messagingSenderId: '920531153302',
    projectId: 'expense-trackeryt',
    storageBucket: 'expense-trackeryt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-kGck5CcEgVhC1xIMJ_aaOgm0XSowOjs',
    appId: '1:920531153302:ios:40c803735331096810edb7',
    messagingSenderId: '920531153302',
    projectId: 'expense-trackeryt',
    storageBucket: 'expense-trackeryt.appspot.com',
    iosBundleId: 'com.example.expenseTrackerFire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-kGck5CcEgVhC1xIMJ_aaOgm0XSowOjs',
    appId: '1:920531153302:ios:c43bfd87c430ae9510edb7',
    messagingSenderId: '920531153302',
    projectId: 'expense-trackeryt',
    storageBucket: 'expense-trackeryt.appspot.com',
    iosBundleId: 'com.example.expenseTrackerFire.RunnerTests',
  );
}
